import { useEffect, useState } from "react";

import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { PageContainer } from "../components/PageContainer";
import { PageHeader } from "../components/PageHeader";
import { StatCard } from "../components/StatCard";
import { Table } from "../components/Table";
import { reportService } from "../services/reportService";
import type { DashboardOverview, ReportRecord } from "../types/report";

const REPORT_TYPES = [
  { label: "Order Summary", value: "order_summary" },
  { label: "Shipment Status", value: "shipment_status" },
  { label: "Revenue", value: "revenue" },
  { label: "Fleet Utilization", value: "fleet_utilization" },
];

export function ReportsPage() {
  const [overview, setOverview] = useState<DashboardOverview | null>(null);
  const [reports, setReports] = useState<ReportRecord[]>([]);
  const [generating, setGenerating] = useState<string | null>(null);
  const [error, setError] = useState("");

  const refreshReports = () => {
    reportService.listReports().then(setReports).catch(() => setReports([]));
  };

  useEffect(() => {
    reportService.getDashboardOverview().then(setOverview).catch(() => setOverview(null));
    refreshReports();
  }, []);

  const handleGenerate = async (reportType: string) => {
    setGenerating(reportType);
    setError("");
    try {
      await reportService.generateReport(reportType);
      refreshReports();
    } catch (err) {
      const detail =
        (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail ??
        "Report generation failed.";
      setError(detail);
    } finally {
      setGenerating(null);
    }
  };

  return (
    <PageContainer>
      <PageHeader
        eyebrow="Reports"
        description="Generate real, database-backed reports covering orders, shipments, revenue, and fleet utilization."
        title="Reports"
      />

      <div className="grid gap-4 md:grid-cols-4">
        <StatCard icon="monitoring" label="Orders Processed" note="Current total order count" value={String(overview?.total_orders ?? 0)} />
        <StatCard icon="payments" label="Revenue" note="Recognized payments" value={`₫${(overview?.revenue ?? 0).toLocaleString("vi-VN")}`} />
        <StatCard icon="schedule" label="Active Shipments" note="Current shipment execution load" value={String(overview?.active_shipments ?? 0)} />
        <StatCard icon="verified" label="Fleet Available" note="Vehicles ready for allocation" value={String(overview?.fleet_available ?? 0)} />
      </div>

      <Card className="p-6">
        <h3 className="text-2xl font-semibold text-text-primary">Generate Report</h3>
        <p className="mt-1 text-sm text-text-secondary">
          Produces a fresh, database-backed snapshot for the selected report type.
        </p>
        <div className="mt-5 flex flex-wrap gap-2">
          {REPORT_TYPES.map((type) => (
            <Button
              disabled={generating === type.value}
              key={type.value}
              onClick={() => handleGenerate(type.value)}
              variant="secondary"
            >
              {generating === type.value ? "Generating..." : type.label}
            </Button>
          ))}
        </div>
        {error && <p className="mt-3 text-sm font-medium text-red-600">{error}</p>}
      </Card>

      <Table
        columns={[
          { header: "Report ID", render: (row) => String(row.report_id) },
          { header: "Type", render: (row) => row.report_type },
          { header: "Generated By", render: (row) => row.generated_by ?? "-" },
          { header: "Generated At", render: (row) => new Date(row.generated_at).toISOString().slice(0, 10) },
          {
            header: "Content",
            render: (row) => (
              <pre className="max-w-xs overflow-x-auto whitespace-pre-wrap text-xs text-text-secondary">
                {row.content ?? "-"}
              </pre>
            ),
          },
        ]}
        data={reports}
      />
    </PageContainer>
  );
}
