import { useEffect, useState } from "react";

import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { PageContainer } from "../components/PageContainer";
import { PageHeader } from "../components/PageHeader";
import { StatCard } from "../components/StatCard";
import { Table } from "../components/Table";
import { reportService } from "../services/reportService";
import type { DashboardOverview, ReportRecord } from "../types/report";

export function ReportsPage() {
  const [overview, setOverview] = useState<DashboardOverview | null>(null);
  const [reports, setReports] = useState<ReportRecord[]>([]);

  useEffect(() => {
    reportService.getDashboardOverview().then(setOverview).catch(() => setOverview(null));
    reportService.listReports().then(setReports).catch(() => setReports([]));
  }, []);

  return (
    <PageContainer>
      <PageHeader
        actions={[{ icon: "download", label: "Export", variant: "primary" }]}
        eyebrow="Reports"
        description="Review logistics performance with responsive reporting cards, visual summaries, and recent order reporting data."
        title="Reports"
      />

      <div className="grid gap-4 md:grid-cols-4">
        <StatCard icon="monitoring" label="Orders Processed" note="Current total order count" value={String(overview?.total_orders ?? 0)} />
        <StatCard icon="payments" label="Revenue" note="Recognized payments" value={`$${(overview?.revenue ?? 0).toFixed(2)}`} />
        <StatCard icon="schedule" label="Active Shipments" note="Current shipment execution load" value={String(overview?.active_shipments ?? 0)} />
        <StatCard icon="verified" label="Fleet Available" note="Vehicles ready for allocation" value={String(overview?.fleet_available ?? 0)} />
      </div>

      <div className="grid gap-4 xl:grid-cols-[1fr_0.95fr]">
        <Card className="p-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-2xl font-semibold text-text-primary">Bar Chart</h3>
              <p className="mt-1 text-sm text-text-secondary">Monthly shipment output by operational lane</p>
            </div>
            <Button variant="ghost">Quarterly</Button>
          </div>
          <div className="mt-8 flex h-[260px] items-end gap-4">
            {[58, 72, 64, 88, 96, 104].map((value, index) => (
              <div key={index} className="flex flex-1 flex-col items-center gap-3">
                <div className="w-full rounded-t-3xl bg-brand-100">
                  <div className="rounded-t-3xl bg-brand-500" style={{ height: `${value * 1.8}px` }} />
                </div>
                <span className="text-sm text-text-secondary">Q{index + 1}</span>
              </div>
            ))}
          </div>
        </Card>

        <Card className="p-6">
          <h3 className="text-2xl font-semibold text-text-primary">Pie Chart</h3>
          <p className="mt-1 text-sm text-text-secondary">Service mix breakdown</p>
          <div className="mt-8 flex flex-col items-center gap-6">
            <div className="h-56 w-56 rounded-full bg-[conic-gradient(#0058BE_0_44%,#7db3f4_44%_71%,#f59e0b_71%_88%,#16a34a_88%_100%)]" />
            <div className="grid w-full gap-3 sm:grid-cols-2">
              {[
                ["Express", "44%"],
                ["Standard", "27%"],
                ["Same Day", "17%"],
                ["Special Handling", "12%"],
              ].map(([label, value]) => (
                <div key={label} className="rounded-2xl bg-brand-50 px-4 py-3">
                  <p className="text-sm text-text-secondary">{label}</p>
                  <p className="mt-1 font-semibold text-text-primary">{value}</p>
                </div>
              ))}
            </div>
          </div>
        </Card>
      </div>

      <Table
        columns={[
          { header: "Report ID", render: (row) => String(row.report_id) },
          { header: "Type", render: (row) => row.report_type },
          { header: "Generated By", render: (row) => row.generated_by ?? "-" },
          { header: "Generated At", render: (row) => new Date(row.generated_at).toISOString().slice(0, 10) },
        ]}
        data={reports}
      />
    </PageContainer>
  );
}
